version: '3.3'
networks:
    myNetwork:
        external:
            name: myNetwork

services:
    peer0_org2:
        image: hyperledger/fabric-peer:1.3.0
        container_name: peer0.org2.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_GOSSIP=DEBUG
            - CORE_LOGGING_MSP=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
            - /var/mynetwork/peer0.org2.example.com:/var/hyperledger/production
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 9051:7051
            - 9053:7053
        networks:
            - myNetwork 
    
    peer1_org2:
        image: hyperledger/fabric-peer:1.3.0
        container_name: peer1.org2.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=myNetwork
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=myNetwork
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_GOSSIP=DEBUG
            - CORE_LOGGING_MSP=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.example.com:7051
            - CORE_PEER_LOCALMSPID=Org2MSP
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
            - /var/mynetwork/peer1.org2.example.com:/var/hyperledger/production
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
              - 10051:7051
              - 10053:7053
        networks:
            - myNetwork 
    
   
